Repository BinaryStudioAcademy/bsa-2021-watchdog, pull requests merged in 2021-07, with the labels that each got.

#6 add core db schema
  docs/db-scheme.drawio
  docs/db_schema.png
Labels: documentation

#8 Feature/create auth service
  frontend/src/app/core/core.module.ts
  frontend/src/app/core/guards/auth.guard.ts
  frontend/src/app/core/helpers/fake-backend.ts
  frontend/src/app/core/models/auth/auth-user.ts
  frontend/src/app/core/models/auth/user-login.ts
  frontend/src/app/core/models/user.ts
  frontend/src/app/core/services/auth.service.ts
Labels: enhancement

#11 Add RabbitMQ
  backend/Watchdog.All.sln
  backend/Watchdog.Core/Watchdog.Core.API/Controllers/SampleController.cs
  backend/Watchdog.Core/Watchdog.Core.API/Startup.cs
  backend/Watchdog.Core/Watchdog.Core.API/appsettings.json
  backend/Watchdog.Core/Watchdog.Core.BLL/Services/QueueService.cs
  backend/Watchdog.Core/Watchdog.Core.BLL/Watchdog.Core.BLL.csproj
  backend/Watchdog.RabbitMQ.Shared/Interfaces/IConsumer.cs
  backend/Watchdog.RabbitMQ.Shared/Interfaces/IProducer.cs
  backend/Watchdog.RabbitMQ.Shared/Models/ConsumerSettings.cs
  backend/Watchdog.RabbitMQ.Shared/Models/ProducerSettings.cs
  backend/Watchdog.RabbitMQ.Shared/Services/Consumer.cs
  backend/Watchdog.RabbitMQ.Shared/Services/Producer.cs
  backend/Watchdog.RabbitMQ.Shared/Watchdog.RabbitMQ.Shared.csproj
Labels: help wanted
